services:
  - type: web
    name: shopci
    runtime: docker
    plan: standard
    region: frankfurt
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
